package medizin.shared.criteria;

public enum PossibleFields {
	KEYWORD, 
	QUESTION_EVENT,
	COMMENT,
	ANSWER_TEXT,
	QUESTION_TEXT,
	QUESTION_SHORT_NAME,
	CREATED_QUESTION_DATE,
	CHANGED_QUESTION_DATE,
	USED_IN_MC_DATE,
	MC,
	AUTHOR,
	REVIEWER,
	IMAGE,
	SOUND,
	VIDEO,
	MEDIA_AVAILABILITY,
	QUESTION_TYPE,
	QUESTION_TYPE_NAME;
}
