// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import medizin.server.domain.Appliance;

privileged aspect Appliance_Roo_JavaBean {
    
    public String Appliance.getShortcut() {
        return this.shortcut;
    }
    
    public void Appliance.setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }
    
}
