// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import medizin.server.domain.Keyword;

privileged aspect Keyword_Roo_JavaBean {
    
    public String Keyword.getName() {
        return this.name;
    }
    
    public void Keyword.setName(String name) {
        this.name = name;
    }
    
}
