// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.QuestionResource;
import medizin.server.domain.QuestionResourceDataOnDemand;
import medizin.server.domain.QuestionResourceIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionResourceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionResourceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionResourceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionResourceIntegrationTest: @Transactional;
    
    @Autowired
    QuestionResourceDataOnDemand QuestionResourceIntegrationTest.dod;
    
    @Test
    public void QuestionResourceIntegrationTest.testCountQuestionResources() {
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", dod.getRandomQuestionResource());
        long count = QuestionResource.countQuestionResources();
        Assert.assertTrue("Counter for 'QuestionResource' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testFindQuestionResource() {
        QuestionResource obj = dod.getRandomQuestionResource();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to provide an identifier", id);
        obj = QuestionResource.findQuestionResource(id);
        Assert.assertNotNull("Find method for 'QuestionResource' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionResource' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testFindAllQuestionResources() {
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", dod.getRandomQuestionResource());
        long count = QuestionResource.countQuestionResources();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionResource', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionResource> result = QuestionResource.findAllQuestionResources();
        Assert.assertNotNull("Find all method for 'QuestionResource' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionResource' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testFindQuestionResourceEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", dod.getRandomQuestionResource());
        long count = QuestionResource.countQuestionResources();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionResource> result = QuestionResource.findQuestionResourceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionResource' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionResource' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testFlush() {
        QuestionResource obj = dod.getRandomQuestionResource();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to provide an identifier", id);
        obj = QuestionResource.findQuestionResource(id);
        Assert.assertNotNull("Find method for 'QuestionResource' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionResource(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionResource' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testMergeUpdate() {
        QuestionResource obj = dod.getRandomQuestionResource();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to provide an identifier", id);
        obj = QuestionResource.findQuestionResource(id);
        boolean modified =  dod.modifyQuestionResource(obj);
        Integer currentVersion = obj.getVersion();
        QuestionResource merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionResource' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", dod.getRandomQuestionResource());
        QuestionResource obj = dod.getNewTransientQuestionResource(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionResource' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionResource' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionResourceIntegrationTest.testRemove() {
        QuestionResource obj = dod.getRandomQuestionResource();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionResource' failed to provide an identifier", id);
        obj = QuestionResource.findQuestionResource(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionResource' with identifier '" + id + "'", QuestionResource.findQuestionResource(id));
    }
    
}
