// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.UserAccessRights;
import medizin.server.domain.UserAccessRightsDataOnDemand;
import medizin.server.domain.UserAccessRightsIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAccessRightsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAccessRightsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAccessRightsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAccessRightsIntegrationTest: @Transactional;
    
    @Autowired
    UserAccessRightsDataOnDemand UserAccessRightsIntegrationTest.dod;
    
    @Test
    public void UserAccessRightsIntegrationTest.testCountUserAccessRightses() {
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", dod.getRandomUserAccessRights());
        long count = UserAccessRights.countUserAccessRightses();
        Assert.assertTrue("Counter for 'UserAccessRights' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testFindUserAccessRights() {
        UserAccessRights obj = dod.getRandomUserAccessRights();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to provide an identifier", id);
        obj = UserAccessRights.findUserAccessRights(id);
        Assert.assertNotNull("Find method for 'UserAccessRights' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAccessRights' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testFindAllUserAccessRightses() {
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", dod.getRandomUserAccessRights());
        long count = UserAccessRights.countUserAccessRightses();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAccessRights', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAccessRights> result = UserAccessRights.findAllUserAccessRightses();
        Assert.assertNotNull("Find all method for 'UserAccessRights' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAccessRights' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testFindUserAccessRightsEntries() {
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", dod.getRandomUserAccessRights());
        long count = UserAccessRights.countUserAccessRightses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAccessRights> result = UserAccessRights.findUserAccessRightsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAccessRights' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAccessRights' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testFlush() {
        UserAccessRights obj = dod.getRandomUserAccessRights();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to provide an identifier", id);
        obj = UserAccessRights.findUserAccessRights(id);
        Assert.assertNotNull("Find method for 'UserAccessRights' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserAccessRights(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserAccessRights' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testMergeUpdate() {
        UserAccessRights obj = dod.getRandomUserAccessRights();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to provide an identifier", id);
        obj = UserAccessRights.findUserAccessRights(id);
        boolean modified =  dod.modifyUserAccessRights(obj);
        Integer currentVersion = obj.getVersion();
        UserAccessRights merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserAccessRights' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", dod.getRandomUserAccessRights());
        UserAccessRights obj = dod.getNewTransientUserAccessRights(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAccessRights' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserAccessRights' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAccessRightsIntegrationTest.testRemove() {
        UserAccessRights obj = dod.getRandomUserAccessRights();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAccessRights' failed to provide an identifier", id);
        obj = UserAccessRights.findUserAccessRights(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAccessRights' with identifier '" + id + "'", UserAccessRights.findUserAccessRights(id));
    }
    
}
