// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import medizin.server.domain.InstitutionDataOnDemand;
import medizin.server.domain.Person;
import medizin.server.domain.PersonDataOnDemand;
import medizin.server.domain.QuestionDataOnDemand;
import medizin.server.domain.QuestionEventDataOnDemand;
import medizin.server.domain.UserAccessRights;
import medizin.server.domain.UserAccessRightsDataOnDemand;
import medizin.shared.AccessRights;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UserAccessRightsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserAccessRightsDataOnDemand: @Component;
    
    private Random UserAccessRightsDataOnDemand.rnd = new SecureRandom();
    
    private List<UserAccessRights> UserAccessRightsDataOnDemand.data;
    
    @Autowired
    InstitutionDataOnDemand UserAccessRightsDataOnDemand.institutionDataOnDemand;
    
    @Autowired
    PersonDataOnDemand UserAccessRightsDataOnDemand.personDataOnDemand;
    
    @Autowired
    QuestionDataOnDemand UserAccessRightsDataOnDemand.questionDataOnDemand;
    
    @Autowired
    QuestionEventDataOnDemand UserAccessRightsDataOnDemand.questionEventDataOnDemand;
    
    public UserAccessRights UserAccessRightsDataOnDemand.getNewTransientUserAccessRights(int index) {
        UserAccessRights obj = new UserAccessRights();
        setAccRights(obj, index);
        setPerson(obj, index);
        return obj;
    }
    
    public void UserAccessRightsDataOnDemand.setAccRights(UserAccessRights obj, int index) {
        AccessRights accRights = AccessRights.class.getEnumConstants()[0];
        obj.setAccRights(accRights);
    }
    
    public void UserAccessRightsDataOnDemand.setPerson(UserAccessRights obj, int index) {
        Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    public UserAccessRights UserAccessRightsDataOnDemand.getSpecificUserAccessRights(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserAccessRights obj = data.get(index);
        Long id = obj.getId();
        return UserAccessRights.findUserAccessRights(id);
    }
    
    public UserAccessRights UserAccessRightsDataOnDemand.getRandomUserAccessRights() {
        init();
        UserAccessRights obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserAccessRights.findUserAccessRights(id);
    }
    
    public boolean UserAccessRightsDataOnDemand.modifyUserAccessRights(UserAccessRights obj) {
        return false;
    }
    
    public void UserAccessRightsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserAccessRights.findUserAccessRightsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserAccessRights' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserAccessRights>();
        for (int i = 0; i < 10; i++) {
            UserAccessRights obj = getNewTransientUserAccessRights(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
