package medizin.client.factory.request;
import medizin.client.request.AnswerRequest;
import medizin.client.request.AnswerToAssQuestionRequest;
import medizin.client.request.AssesmentQuestionRequest;
import medizin.client.request.AssesmentRequest;
import medizin.client.request.CommentRequest;
import medizin.client.request.DoctorRequest;
import medizin.client.request.InstitutionRequest;
import medizin.client.request.KeywordRequest;
import medizin.client.request.MatrixValidityRequest;
import medizin.client.request.McRequest;
import medizin.client.request.PersonRequest;
import medizin.client.request.QuestionEventRequest;
import medizin.client.request.QuestionRequest;
import medizin.client.request.QuestionResourceRequest;
import medizin.client.request.QuestionSumPerPersonRequest;
import medizin.client.request.QuestionTypeCountPerExamRequest;
import medizin.client.request.QuestionTypeRequest;
import medizin.client.request.StaticContentRequest;
import medizin.client.request.StaticToAssesmentRequest;
import medizin.client.request.StudentToAssesmentRequest;
import medizin.client.request.UserAccessRightsRequest;
import medizin.server.domain.UserAccessRights;

import com.google.web.bindery.requestfactory.shared.LoggingRequest;
import com.google.web.bindery.requestfactory.shared.RequestFactory;

/**
 * "API generated" factory interface to build request objects for the methods of
 * {@link com.google.gwt.sample.expenses.server.domain}. Client code can
 * GWT.create() an instance of this interface to build and fire request objects.
 * <p>
 * IRL this interface will be generated by a JPA-savy tool run before
 * compilation.
 */

public interface McAppRequestFactory extends RequestFactory {

	
	/**
	 * Return a GWT logging request.
	 */
	LoggingRequest loggingRequest();
	
	AnswerRequest answerRequest();

    AnswerToAssQuestionRequest answerToAssQuestionRequest();

    AssesmentRequest assesmentRequest();

    AssesmentQuestionRequest assesmentQuestionRequest();

    CommentRequest commentRequest();

    InstitutionRequest institutionRequest();

    KeywordRequest keywordRequest();

    McRequest mcRequest();

    PersonRequest personRequest();

    QuestionEventRequest questionEventRequest();

    QuestionRequest questionRequest();
    
    QuestionResourceRequest questionResourceRequest(); 

    QuestionSumPerPersonRequest questionSumPerPersonRequest();

    QuestionTypeCountPerExamRequest questionTypeCountPerExamRequest();

    QuestionTypeRequest questionTypeRequest();

    StaticContentRequest staticContentRequest();

    StaticToAssesmentRequest staticToAssesmentRequest();

    DoctorRequest doctorRequest();
    
    UserAccessRightsRequest userAccessRightsRequest();
    
    MatrixValidityRequest MatrixValidityRequest();
    
    StudentToAssesmentRequest studentToAssesmentRequest();
}
