// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package medizin.client.ui.view.roo;

import java.util.Set;

import medizin.client.proxy.KeywordProxy;

import com.google.gwt.editor.client.LeafValueEditor;
import com.google.gwt.editor.client.ValueAwareEditor;
import com.google.gwt.user.client.ui.Composite;

public abstract class KeywordSetEditor_Roo_Gwt extends Composite implements ValueAwareEditor<Set<KeywordProxy>>, LeafValueEditor<Set<KeywordProxy>> {
}
