package medizin.shared;

public enum Status {
	NEW, 
	CORRECTION_FROM_ADMIN,
	CORRECTION_FROM_REVIEWER,
	CORRECTED, 
	ACCEPTED_ADMIN,
	ACCEPTED_REVIEWER,
	ACTIVE, 
	DEACTIVATED,
	EDITED_BY_ADMIN,
	EDITED_BY_REVIEWER,
	CREATIVE_WORK;
}
